drop table if exists VEICULO;

create table VEICULO (
    MARCA VARCHAR(50),
    MODELO VARCHAR(50),
    MATRICULA VARCHAR(20) PRIMARY KEY,
    CONSUMO DOUBLE
);

insert into VEICULO (MARCA, MODELO, MATRICULA, CONSUMO) VALUES ('FORD', 'FIESTA', '34-FQ-06', 4.6);
insert into VEICULO (MARCA, MODELO, MATRICULA, CONSUMO) VALUES ('FIAT', 'PUNTO', '35-FQ-07', 5.0);
insert into VEICULO (MARCA, MODELO, MATRICULA, CONSUMO) VALUES ('PEUGEOT', '308', 'AA-22-CC', 6.3);
insert into VEICULO (MARCA, MODELO, MATRICULA, CONSUMO) VALUES ('BMW', '320', '99-99-ZZ', 7.4);
insert into VEICULO (MARCA, MODELO, MATRICULA, CONSUMO) VALUES ('SEAT', 'LEON', 'ZZ-99-99', 8.5);
